// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/ngb/d/multiselect-list.js', ['ngb.d.MultiselectList'], [], false);
goog.addDependency('../../../../src/ngb/d/patient-modal.js', ['ngb.d.PatientModal'], [], false);
goog.addDependency('../../../../src/ngb/ngb.js', ['ngb'], ['ngb.d.MultiselectList', 'ngb.d.PatientModal', 'ngb.s.Modal'], false);
goog.addDependency('../../../../src/ngb/s/modal.js', ['ngb.s.Modal', 'ngb.s.ModalController', 'ngb.s.ModalProvider'], ['ngb.d.PatientModal'], false);
