// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/ngb/d/modal.js', ['ngb.d.Modal'], [], false);
goog.addDependency('../../../../src/ngb/d/multiselect-list.js', ['ngb.d.MultiselectList'], [], false);
goog.addDependency('../../../../src/ngb/ngb.js', ['ngb'], ['ngb.d.MultiselectList', 'ngb.s.Modal'], false);
goog.addDependency('../../../../src/ngb/s/modal.js', ['ngb.s.Modal', 'ngb.s.ModalProvider'], [], false);
